{% set name = "BELY-API" %}
{% set version = "2024.6" %}

package:
  name: "{{ name|lower }}"  
  version: "{{ version }}"

source:
  path: ./src

requirements:  
  build:
    - pip
    - python>3.10
  run:
    - python
    - python-dateutil
    - six
    - urllib3
    - certifi

test:
  imports:
    - BelyApiFactory

about:
  home: "https://git.lbl.gov/controls/hla/bely"
  license: "Copyright (c) UChicago Argonne, LLC. All rights reserved."    
  summary: "Library Containing Component DB APIs"
