# Copyright (c) UChicago Argonne, LLC. All rights reserved.
# See LICENSE file.
CdbSoftwareVersion=Development 
CdbSoftwareVersionUrl=https://git.lbl.gov/controls/hla/logr
CdbBugReportUrl=https://git.lbl.gov/controls/hla/logr/-/issues/new
CdbCodeRepository=https://git.lbl.gov/controls/hla/logr
CdbPortalTitle=Logbook Portal
CdbCopyrightNotice=2024 UChicago Argonne, LLC

SelectDataTableNumberOfRows=10
DialogDataTableNumberOfRows=5
DialogSearchResultsDataTableNumberOfRows=19
DisplayFiltersForViewDataTablesWithNumberOfRows=10
InventoryNoScrollboxMaximum=6
MdReorderNoScrollboxMaximum=22
EnabledMAARCDomainFunctionality=True
# See github issue #1021 (will need to restore this subscription). 
EnabledMachineInventoryFunctionality=False
