LOCK TABLES `setting_type` WRITE;
SET SESSION FOREIGN_KEY_CHECKS=0;
/*!40000 ALTER TABLE `setting_type` DISABLE KEYS */;
INSERT INTO `setting_type` VALUES
(1,'ItemDomainLogbook.List.Display.NumberOfItemsPerPage','Display specified number of items per page.','25'),
(2,'ItemDomainLogbook.List.Display.Id','Display id.','false'),
(3,'ItemDomainLogbook.List.Display.Description','Display description.','false'),
(4,'ItemDomainLogbook.List.Display.ItemType','Display item type(system).','true'),
(5,'ItemDomainLogbook.List.Display.OwnerUser','Display owner user.','false'),
(6,'ItemDomainLogbook.List.Display.OwnerGroup','Display owner group.','false'),
(7,'ItemDomainLogbook.List.Display.CreatedUser','Display created user.','false'),
(8,'ItemDomainLogbook.List.Display.CreatedTime','Display creation time.','true'),
(9,'ItemDomainLogbook.List.Display.ModifiedByUser','Display modified by user.','true'),
(10,'ItemDomainLogbook.List.Display.ModifiedTime','Display last modified time.','true'),
(11,'ItemDomainLogbook.List.Display.PropertyTypeId1','Display property value for property type id #1.',''),
(12,'ItemDomainLogbook.List.Display.PropertyTypeId2','Display property value for property type id #2.',''),
(13,'ItemDomainLogbook.List.Display.PropertyTypeId3','Display property value for property type id #3.',''),
(14,'ItemDomainLogbook.List.Display.PropertyTypeId4','Display property value for property type id #4.',''),
(15,'ItemDomainLogbook.List.Display.PropertyTypeId5','Display property value for property type id #5.',''),
(16,'ItemDomainLogbook.Home.EntityTypeId1','1st entityType Id to show up on the home page.',''),
(17,'ItemDomainLogbook.Home.EntityTypeId2','2nd entityType Id to show up on the home page.',''),
(18,'ItemDomainLogbook.Home.EntityTypeId3','3rd entityType Id to show up on the home page.',''),
(999,'DomainEntity.Detail.Display.GalleryViewableDocuments','Display viewable documents in the gallery.','true'),
(1000,'AllowedPropertyValue.List.Display.Description','Display allowed property value description.','false'),
(1001,'AllowedPropertyValue.List.Display.Id','Display allowed property value id.','false'),
(1002,'AllowedPropertyValue.List.Display.NumberOfItemsPerPage','Display specified number of items per page.','25'),
(1003,'AllowedPropertyValue.List.Display.SortOrder','Display allowed property value sort order.','true'),
(1004,'AllowedPropertyValue.List.Display.Units','Display allowed property value units.','true'),
(1005,'AllowedPropertyValue.List.FilterBy.Description','Filter for allowed property value description.',NULL),
(1006,'AllowedPropertyValue.List.FilterBy.SortOrder','Filter for allowed property value class sort order.',NULL),
(1007,'AllowedPropertyValue.List.FilterBy.Units','Filter for allowed property value units.',NULL),
(1008,'AllowedPropertyValue.List.FilterBy.Value','Filter for allowed property value.',NULL),
(4000,'ItemSource.List.Display.ContactInfo','Display component source contact info.','false'),
(4001,'ItemSource.List.Display.Cost','Display component cost.','true'),
(4002,'ItemSource.List.Display.Description','Display component source description.','true'),
(4003,'ItemSource.List.Display.Id','Display component source id.','false'),
(4004,'ItemSource.List.Display.IsManufacturer','Display component source manufacturer designation.','true'),
(4005,'ItemSource.List.Display.IsVendor','Display component source vendor designation.','true'),
(4006,'ItemSource.List.Display.NumberOfItemsPerPage','Display specified number of items per page.','25'),
(4007,'ItemSource.List.Display.PartNumber','Display component part number.','true'),
(4008,'ItemSource.List.Display.Url','Display component source URL.','false'),
(4009,'ItemSource.List.FilterBy.ContactInfo','Filter for component sources by contact info.',NULL),
(4010,'ItemSource.List.FilterBy.Cost','Filter for component sources by cost.',NULL),
(4011,'ItemSource.List.FilterBy.Description','Filter for component sources by description.',NULL),
(4012,'ItemSource.List.FilterBy.IsManufacturer','Filter for component sources by manufacturer designation.',NULL),
(4013,'ItemSource.List.FilterBy.IsVendor','Filter for component sources by vendor designation.',NULL),
(4014,'ItemSource.List.FilterBy.PartNumber','Filter for component sources by part number.',NULL),
(4015,'ItemSource.List.FilterBy.SourceName','Filter for component sources by name.',NULL),
(4016,'ItemSource.List.FilterBy.Url','Filter for component sources by URL.',NULL),
(5000,'ItemType.List.Display.Description','Display component type description.','true'),
(5001,'ItemType.List.Display.Id','Display component type id.','false'),
(5002,'ItemType.List.Display.NumberOfItemsPerPage','Display specified number of items per page.','25'),
(5003,'ItemType.List.FilterBy.Description','Filter for component type description.',NULL),
(5004,'ItemType.List.FilterBy.Name','Filter for component type name.',NULL),
(6000,'ItemCategory.List.Display.Description','Display item category description.','true'),
(6001,'ItemCategory.List.Display.Id','Display item category id.','false'),
(6002,'ItemCategory.List.Display.NumberOfItemsPerPage','Display specified number of items per page.','25'),
(6003,'ItemCategory.List.FilterBy.Description','Filter for item category description.',NULL),
(6004,'ItemCategory.List.FilterBy.Name','Filter for item category name.',NULL),
(7000,'Item.Member.List.Display.NumberOfItemsPerPage','Display specified number of items per page.','25'),
(7001,'Item.Member.List.Display.Id','Display design id.','false'),
(7002,'Item.Member.List.Display.Description','Display design description.','true'),
(7003,'Item.Member.List.Display.OwnerUser','Display owner username.','true'),
(7004,'Item.Member.List.Display.OwnerGroup','Display owner group name.','true'),
(7005,'Item.Member.List.Display.CreatedByUser','Display created by username.','false'),
(7006,'Item.Member.List.Display.CreatedOnDateTime','Display created on date/time.','false'),
(7007,'Item.Member.List.Display.LastModifiedByUser','Display last modified by username.','false'),
(7008,'Item.Member.List.Display.LastModifiedOnDateTime','Display last modified on date/time.','false'),
(8000,'ItemElement.List.Display.ChildDesign','Display child design.','false'),
(8001,'ItemElement.List.Display.Component','Display component.','false'),
(8002,'ItemElement.List.Display.ComponentType','Display component type.','false'),
(8003,'ItemElement.List.Display.CreatedByUser','Display created by username.','false'),
(8004,'ItemElement.List.Display.CreatedOnDateTime','Display created on date/time.','false'),
(8005,'ItemElement.List.Display.Description','Display design element description.','false'),
(8006,'ItemElement.List.Display.FlatTableView','Display flat table view for design element list.','true'),
(8007,'ItemElement.List.Display.Id','Display design element id.','false'),
(8008,'ItemElement.List.Display.LastModifiedByUser','Display last modified by username.','false'),
(8009,'ItemElement.List.Display.LastModifiedOnDateTime','Display last modified on date/time.','false'),
(8010,'ItemElement.List.Display.Location','Display location.','false'),
(8011,'ItemElement.List.Display.NumberOfItemsPerPage','Display specified number of items per page.','25'),
(8012,'ItemElement.List.Display.OwnerUser','Display owner username.','true'),
(8013,'ItemElement.List.Display.OwnerGroup','Display owner group name.','true'),
(8014,'ItemElement.List.Display.SortOrder','Display design element sort order.','false'),
(8015,'ItemElement.List.Display.RowColor','Display design element row color.','true'),
(8016,'ItemElement.List.Display.PropertyTypeId1','Display property value for property type id #1.',''),
(8017,'ItemElement.List.Display.PropertyTypeId2','Display property value for property type id #2.',''),
(8018,'ItemElement.List.Display.PropertyTypeId3','Display property value for property type id #3.',''),
(8019,'ItemElement.List.Display.PropertyTypeId4','Display property value for property type id #4.',''),
(8020,'ItemElement.List.Display.PropertyTypeId5','Display property value for property type id #5.',''),
(8021,'ItemElement.List.Display.RowExpansion','Display row expansion.','true'),
(8022,'ItemElement.List.Load.RowExpansionPropertyValue','Load property values for row expansions.','true'),
(8023,'ItemElement.List.Display.BillOfMaterialsActionColumn','Display design element list action column in the child design bill of materials.','false'),
(8024,'ItemElement.List.SortBy.PropertyTypeId','Allow user to sort using property type id or the default sort order(NULL)',NULL),
(8025,'ItemElement.List.FilterBy.ChildDesign','Filter for child design.',NULL),
(8026,'ItemElement.List.FilterBy.Component','Filter for component.',NULL),
(8027,'ItemElement.List.FilterBy.ComponentType','Filter for component type.',NULL),
(8028,'ItemElement.List.FilterBy.CreatedByUser','Filter for design elements that were created by username.',NULL),
(8029,'ItemElement.List.FilterBy.CreatedOnDateTime','Filter for design elements that were created on date/time.',NULL),
(8030,'ItemElement.List.FilterBy.Description','Filter for design elements by description.',NULL),
(8031,'ItemElement.List.FilterBy.LastModifiedByUser','Filter for design elements that were last modified by username.',NULL),
(8032,'ItemElement.List.FilterBy.LastModifiedOnDateTime','Filter for design elements that were last modified on date/time.',NULL),
(8033,'ItemElement.List.FilterBy.Location','Filter for component.',NULL),
(8034,'ItemElement.List.FilterBy.Name','Filter for design elements by name.',NULL),
(8035,'ItemElement.List.FilterBy.OwnerUser','Filter for design elements by owner username.',NULL),
(8036,'ItemElement.List.FilterBy.OwnerGroup','Filter for design elements by owner group name.',NULL),
(8037,'ItemElement.List.FilterBy.SortOrder','Filter for design elements by sort order.',NULL),
(8038,'ItemElement.List.Display.SimpleViewPartName','Display part name (element name) on the simple view.','true'),
(8039,'ItemElement.List.Display.SimpleViewPartDescription','Display part description (element description) on the simple view.','true'),
(9000,'Log.List.Display.Attachments','Display log entry attachments.','true'),
(9001,'Log.List.Display.EnteredOnDateTime','Display log entry entered on date/time.','false'),
(9002,'Log.List.Display.EnteredByUser','Display log entry entered by user.','true'),
(9003,'Log.List.Display.Id','Display log entry id.','false'),
(9004,'Log.List.Display.NumberOfItemsPerPage','Display specified number of items per page.','25'),
(9005,'Log.List.Display.Topic','Display log topic.','true'),
(9006,'Log.List.FilterBy.EnteredOnDateTime','Filter for log entry entered on date/time.',NULL),
(9007,'Log.List.FilterBy.EnteredByUser','Filter for log entry entered by user.',NULL),
(9008,'Log.List.FilterBy.Text','Filter for log entry text.',NULL),
(9009,'Log.List.FilterBy.Topic','Filter for log topic.',NULL),
(9010,'Log.List.Display.EffectiveFromDateTime','Display effective from date/time','true'),
(9011,'Log.List.Display.EffectiveToDateTime','Display effective to date/time','false'),
(10000,'PropertyType.List.Display.Category','Display property type category.','true'),
(10001,'PropertyType.List.Display.DefaultUnits','Display property type default units.','false'),
(10002,'PropertyType.List.Display.DefaultValue','Display property type default value.','false'),
(10003,'PropertyType.List.Display.Description','Display property type description.','true'),
(10004,'PropertyType.List.Display.Handler','Display property type class handler.','true'),
(10005,'PropertyType.List.Display.Id','Display property type id.','false'),
(10006,'PropertyType.List.Display.NumberOfItemsPerPage','Display specified number of items per page.','25'),
(10007,'PropertyType.List.FilterBy.Category','Filter for property type category.',NULL),
(10008,'PropertyType.List.FilterBy.DefaultUnits','Filter for property type default units.',NULL),
(10009,'PropertyType.List.FilterBy.DefaultValue','Filter for property type default value.',NULL),
(10010,'PropertyType.List.FilterBy.Description','Filter for property type description.',NULL),
(10011,'PropertyType.List.FilterBy.Handler','Filter for property type class handler.',NULL),
(10012,'PropertyType.List.FilterBy.Name','Filter for property type name.',NULL),
(11000,'PropertyTypeCategory.List.Display.Description','Display property type category description.','true'),
(11001,'PropertyTypeCategory.List.Display.Id','Display property type category id.','false'),
(11002,'PropertyTypeCategory.List.Display.NumberOfItemsPerPage','Display specified number of items per page.','25'),
(11003,'PropertyTypeCategory.List.FilterBy.Description','Filter for property type category description.',NULL),
(11004,'PropertyTypeCategory.List.FilterBy.Name','Filter for property type category name.',NULL),
(12000,'PropertyTypeHandler.List.Display.Description','Display property type handler description.','true'),
(12001,'PropertyTypeHandler.List.Display.Id','Display property type handler id.','false'),
(12002,'PropertyTypeHandler.List.Display.NumberOfItemsPerPage','Display specified number of items per page.','25'),
(12003,'PropertyTypeHandler.List.FilterBy.Description','Filter for property type handler description.',NULL),
(12004,'PropertyTypeHandler.List.FilterBy.Name','Filter for property type handler name.',NULL),
(13000,'PropertyValue.List.Display.Description','Display value entry\ndescription.','true'),
(13001,'PropertyValue.List.Display.EnteredOnDateTime','Display value entry entered on date/time.','false'),
(13002,'PropertyValue.List.Display.EnteredByUser','Display value entry entered by user.','false'),
(13003,'PropertyValue.List.Display.Id','Display property value entry id.','false'),
(13004,'PropertyValue.List.Display.IsDynamic','Display dynamic property type designation.','false'),
(13005,'PropertyValue.List.Display.IsUserWriteable','Display user-writeable property type designation.','false'),
(13006,'PropertyValue.List.Display.NumberOfItemsPerPage','Display specified number of items per page.','25'),
(13007,'PropertyValue.List.Display.Tag','Display property value tag.','true'),
(13008,'PropertyValue.List.Display.TypeCategory','Display property value type category.','false'),
(13009,'PropertyValue.List.Display.Units','Display value units.','false'),
(13010,'PropertyValue.List.FilterBy.Description','Filter for value description.',NULL),
(13011,'PropertyValue.List.FilterBy.EnteredOnDateTime','Filter for value entry entered on date/time.',NULL),
(13012,'PropertyValue.List.FilterBy.EnteredByUser','Filter for value entry entered by user.',NULL),
(13013,'PropertyValue.List.FilterBy.IsDynamic','Filter for dynamic property value designation.',NULL),
(13014,'PropertyValue.List.FilterBy.IsUserWriteable','Filter for user-writeable property value designation.',NULL),
(13015,'PropertyValue.List.FilterBy.Tag','Filter for property value tag.',NULL),
(13016,'PropertyValue.List.FilterBy.Type','Filter for property value type.',NULL),
(13017,'PropertyValue.List.FilterBy.TypeCategory','Filter for property value type category.',NULL),
(13018,'PropertyValue.List.FilterBy.Units','Filter for value units.',NULL),
(13019,'PropertyValue.List.FilterBy.Value','Filter for value entry.',NULL),
(13020,'PropertyValue.List.Display.EffectiveFromDateTime','Display value entry for effective from date/time.','false'),
(13021,'PropertyValue.List.Display.EffectiveToDateTime','Display value entry for effective to date/time.','false'),
(14000,'PropertyValueHistory.List.Display.Description','Display value entry description.','true'),
(14001,'PropertyValueHistory.List.Display.EnteredOnDateTime','Display value entry entered on date/time.','true'),
(14002,'PropertyValueHistory.List.Display.EnteredByUser','Display value entry entered by user.','true'),
(14003,'PropertyValueHistory.List.Display.Id','Display property value entry id.','false'),
(14004,'PropertyValueHistory.List.Display.NumberOfItemsPerPage','Display specified number of items per page.','25'),
(14005,'PropertyValueHistory.List.Display.Tag','Display value tag.','true'),
(14006,'PropertyValueHistory.List.Display.Units','Display value units.','true'),
(14007,'PropertyValueHistory.List.FilterBy.Description','Filter for value description.',NULL),
(14008,'PropertyValueHistory.List.FilterBy.EnteredOnDateTime','Filter for value entry entered on date/time.',NULL),
(14009,'PropertyValueHistory.List.FilterBy.EnteredByUser','Filter for value entry entered by user.',NULL),
(14010,'PropertyValueHistory.List.FilterBy.Tag','Filter for value tag.',NULL),
(14011,'PropertyValueHistory.List.FilterBy.Units','Filter for value units.',NULL),
(14012,'PropertyValueHistory.List.FilterBy.Value','Filter for value entry.',NULL),
(14013,'PropertyValueHistory.List.Display.EffectiveFromDateTime','Display value entry for effective from date/time.','false'),
(14014,'PropertyValueHistory.List.Display.EffectiveToDateTime','Display value entry for effective to date/time.','false'),
(15000,'Search.CaseInsensitive','Case insensitive search.','true'),
(15001,'Search.Display.ItemDomainCatalog','Display search result for catalog items.','true'),
(15002,'Search.Display.ItemDomainInventory','Display search result for inventory items.','true'),
(15003,'Search.Display.ItemDomainLocation','Display search result for location items.','false'),
(15004,'Search.Display.ItemTypes','Display search result for component types.','false'),
(15005,'Search.Display.ItemCategories','Display search result for component type categories.','false'),
(15006,'Search.Display.ItemElements','Display search result for item  elements.','false'),
(15007,'Search.Display.NumberOfItemsPerPage','Display specified number of items per page.','25'),
(15008,'Search.Display.PropertyTypes','Display search result for property types.','false'),
(15009,'Search.Display.PropertyTypeCategories','Display search result for property type categories.','false'),
(15010,'Search.Display.Sources','Display search result for sources.','false'),
(15011,'Search.Display.Users','Display search result for users.','false'),
(15012,'Search.Display.UserGroups','Display search result for user groups.','false'),
(15013,'Search.DisplayItemDomainMachineDesign','Display search result for machine design items','true'),
(15014,'Search.Display.ItemDomainCableCatalog','Display search result for cable catalog items.','true'),
(15015,'Search.Display.ItemDomainCableInventory','Display search result for cable inventory items.','true'),
(15016,'Search.Display.ItemDomainCableDesign','Display search result for cable design items.','true'),
(15017,'Search.Display.ItemDomainMAARC','Display search result for MAARC items','false'),
(16000,'Source.List.Display.ContactInfo','Display source contact info.','true'),
(16001,'Source.List.Display.Description','Display source description.','true'),
(16002,'Source.List.Display.Url','Display source URL.','true'),
(16003,'Source.List.Display.Id','Display source id.','false'),
(16004,'Source.List.Display.NumberOfItemsPerPage','Display specified number of items per page.','25'),
(16005,'Source.List.FilterBy.ContactInfo','Filter for source contact info.',NULL),
(16006,'Source.List.FilterBy.Description','Filter for source description.',NULL),
(16007,'Source.List.FilterBy.Name','Filter for source name.',NULL),
(16008,'Source.List.FilterBy.Url','Filter for source URL.',NULL),
(17000,'UserInfo.List.Display.Description','Display user description.','false'),
(17001,'UserInfo.List.Display.Email','Display user email.','true'),
(17002,'UserInfo.List.Display.FirstName','Display user first name.','true'),
(17003,'UserInfo.List.Display.Id','Display user id.','false'),
(17004,'UserInfo.List.Display.Groups','Display user groups.','true'),
(17005,'UserInfo.List.Display.LastName','Display user last name.','true'),
(17006,'UserInfo.List.Display.MiddleName','Display user middle name.','false'),
(17007,'UserInfo.List.Display.NumberOfItemsPerPage','Display specified number of items per page.','25'),
(17008,'UserInfo.List.FilterBy.Description','Filter for user description.',NULL),
(17009,'UserInfo.List.FilterBy.Email','Filter for user email.',NULL),
(17010,'UserInfo.List.FilterBy.FirstName','Filter for user first name.',NULL),
(17011,'UserInfo.List.FilterBy.Groups','Filter for user groups.',NULL),
(17012,'UserInfo.List.FilterBy.LastName','Filter for user last name.',NULL),
(17013,'UserInfo.List.FilterBy.MiddleName','Filter for user middle name.',NULL),
(17014,'UserInfo.List.FilterBy.Username','Filter for username.',NULL),
(18000,'UserGroup.List.Display.Description','Display user group description.','true'),
(18001,'UserGroup.List.Display.Id','Display user group id.','false'),
(18002,'UserGroup.List.Display.NumberOfItemsPerPage','Display specified number of items per page.','25'),
(18003,'UserGroup.List.FilterBy.Description','Filter for user group description.',NULL),
(18004,'UserGroup.List.FilterBy.Name','Filter for user group name.',NULL),
(19000,'UserSetting.List.Display.NumberOfItemsPerPage','Display specified number of items per page.','25'),
(20000,'ItemProject.System.ItemProjectId','Default item project to be used in the system',NULL);
/*!40000 ALTER TABLE `setting_type` ENABLE KEYS */;
UNLOCK TABLES;
